/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as FormattingRouteImport } from './routes/formatting'
import { Route as IndexRouteImport } from './routes/index'

const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const FormattingRoute = FormattingRouteImport.update({
  id: '/formatting',
  path: '/formatting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formatting': typeof FormattingRoute
  '/planning': typeof PlanningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formatting': typeof FormattingRoute
  '/planning': typeof PlanningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formatting': typeof FormattingRoute
  '/planning': typeof PlanningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/formatting' | '/planning'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/formatting' | '/planning'
  id: '__root__' | '/' | '/formatting' | '/planning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormattingRoute: typeof FormattingRoute
  PlanningRoute: typeof PlanningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formatting': {
      id: '/formatting'
      path: '/formatting'
      fullPath: '/formatting'
      preLoaderRoute: typeof FormattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormattingRoute: FormattingRoute,
  PlanningRoute: PlanningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
